### PR TITLE
Fix UV pool overflow and cancel outstanding HTTP requests on DNS success

### LINKED ISSUE #40: Cancel outstanding HTTP requests on DNS success
[Issuehunt badges](https://issuehunt.io/r/sindresorhus/is-online/issues/40)

Adding this issue here so we don't forget about it.

Details in https://github.com/sindresorhus/is-online/pull/39#issuecomment-279813937, it' currently blocked by https://github.com/sindresorhus/got/issues/274.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $40.00)

- [issuehunt issuehunt](https://issuehunt.io/u/issuehunt) ($40.00)

### Submitted pull Requests
- [#65 if one check is successful, other checks are now cancelled](https://issuehunt.io/r/sindresorhus/is-online/pull/65)
- [#69 Query leak](https://issuehunt.io/r/sindresorhus/is-online/pull/69)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/is-online/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### LINKED ISSUE #47: DNS resolutions overflow UV pool
[Issuehunt badges](https://issuehunt.io/r/sindresorhus/is-online/issues/47)

I found situation when using is-online gives negative consequences on my system.

**Preconditions**

- your network is offline
- you use is-online periodically by timer

**What will happen**

is-online uses domain name for network checking, it means DNS resolution will be done first. Since network is actually offline, DNS resolution is becoming very long operation, which will block thread of UV pool. Since we run it on regular basis (in my case I ran it every 5 seconds), your UV pool overflows after some time. By default UV pool size is 4.
After UV pool is overflown, all UV operations will be queued (like fs.* functions), which may cause significant delays of their execution. In my case after 20 minutes of operation, queue increased to 50-70 operations, which gave me almost never ending new operations (like fs.readFile or any other).

I'd suggest avoid DNS resolution here (in my project I implemented 8.8.8.8:53 connection instead) or cancel DNS resolution requests when timeout happens.

Information about UV pool can be found here
https://www.future-processing.pl/blog/on-problems-with-threads-in-node-js/

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $30.00)

- [issuehunt issuehunt](https://issuehunt.io/u/issuehunt) ($30.00)

### Submitted pull Requests
- [#69 Query leak](https://issuehunt.io/r/sindresorhus/is-online/pull/69)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/is-online/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### PR DESCRIPTION
**Pull request by LuKks**
Fix #47 
(edit: it also should fix #40)

It needs https://github.com/sindresorhus/public-ip/pull/42 merged first.
Later it needs the update at that version of `public-ip`, let's say 4.0.1.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Referenced issues

This pull request has been submitted to:
- [#47: DNS resolutions overflow UV pool](https://issuehunt.io/repos/24239833/issues/47)
- [#40: Cancel outstanding HTTP requests on DNS success](https://issuehunt.io/repos/24239833/issues/40)
---

IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### CODE REVIEW

**Comment by LuKks** [comment]
I think we can also fix #40, I probably need to see about to also cancel the `got` request.

File: index.js [hunk 1]
```diff
@@ -22,19 +38,35 @@ const isOnline = options => {
...
+			const query = appleCheck(options);
+			queries.push(query);
+			await query;
+			return true;
+		})()
 	]);
 
-	return pTimeout(promise, options.timeout).catch(() => false);
+	return pTimeout(promise, options.timeout).catch(() => {
+		queries.forEach(query => {
```
Comment (sindresorhus) [inline index.js]: Use a `for-of` loop.

File: index.js [hunk 2]
```diff
@@ -4,15 +4,31 @@ const publicIp = require('public-ip');
...
 		headers: {
 			'user-agent': 'CaptiveNetworkSupport/1.0 wispr'
 		}
 	});
 
-	return /Success/.test(body || '') || Promise.reject();
+	const promise = (async () => {
+		try {
+			const {body} = await gotPromise;
+			if (!/Success/.test(body || '')) {
```
Comment (sindresorhus) [inline index.js]:
```suggestion
			if ((body || '').includes('Success')) {
```

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/public-ip/releases/tag/v4.0.1
